### ISSUE TITLE
Getting Started Issues

### ISSUE THREAD

**Issue by AdrienGiboire** [romuloalves/dat-react-native#1]
Hey there!

I wanted to take a look at what you've done. I've almost no experience with react native. I found your project because I had something in mind and stumbled upon here while looking for existing work mixing dat and react native.

I have had a couple of issues, some I could not fix, while running your project locally.

First, I had to run JDK 8 otherwise, I just kept having various issues with gradle. Which led me to have to install old Android SDK, version 23. Is it normal? I give you the details so maybe you will spot what I messed up :)
Second, I have this error in metro bundler: 

```
Loading dependency graph...(node:72826) UnhandledPromiseRejectionWarning: Error: jest-haste-map: @providesModule naming collision:
  Duplicate module name: dat-react-native-server
  Paths: /Users/adrien/code/dat-react-native/ios/build/Build/Products/Debug-iphonesimulator/beakerReactNative.app/nodejs-project/package.json collides with /Users/adrien/code/dat-react-native/nodejs-assets/nodejs-project/package.json

This error is caused by a @providesModule declaration with the same name across two different files.
    at setModule (/Users/adrien/code/dat-react-native/node_modules/metro/node_modules/jest-haste-map/build/index.js:446:17)
    at workerReply (/Users/adrien/code/dat-react-native/node_modules/metro/node_modules/jest-haste-map/build/index.js:496:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:72826) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:72826) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I thought I could take a look to how to fix this but then I thought maybe you would have an idea because you obviously don't have this conflict on your side.

**Edit**: I have found a reference to Android SDK 23 in `build.gradle`, which makes it weird that it then tries to install Android SDK 26…

```
$ react-native run-android

Scanning folders for symlinks in /Users/adrien/code/dat-react-native/node_modules (23ms)
Starting JS server...
Building and installing the app on the device (cd android && ./gradlew installDebug)...
File /Users/adrien/.android/repositories.cfg could not be loaded.
Checking the license for package Android SDK Platform 23 in /Users/adrien/Library/Android/sdk/licenses
License for package Android SDK Platform 23 accepted.
Preparing "Install Android SDK Platform 23".
"Install Android SDK Platform 23" ready.
Finishing "Install Android SDK Platform 23"
Installing Android SDK Platform 23 in /Users/adrien/Library/Android/sdk/platforms/android-23
"Install Android SDK Platform 23" complete.

…

Checking the license for package Android SDK Build-Tools 26.0.3 in /Users/adrien/Library/Android/sdk/licenses
License for package Android SDK Build-Tools 26.0.3 accepted.
Preparing "Install Android SDK Build-Tools 26.0.3".
"Install Android SDK Build-Tools 26.0.3" ready.
Finishing "Install Android SDK Build-Tools 26.0.3"
Installing Android SDK Build-Tools 26.0.3 in /Users/adrien/Library/Android/sdk/build-tools/26.0.3
"Install Android SDK Build-Tools 26.0.3" complete.
Checking the license for package Android SDK Platform 26 in /Users/adrien/Library/Android/sdk/licenses
License for package Android SDK Platform 26 accepted.
Preparing "Install Android SDK Platform 26".
"Install Android SDK Platform 26" ready.
Finishing "Install Android SDK Platform 26"
Installing Android SDK Platform 26 in /Users/adrien/Library/Android/sdk/platforms/android-26
"Install Android SDK Platform 26" complete.

…

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > A problem occurred configuring project ':react-native-fs'.
      > Could not resolve all dependencies for configuration ':react-native-fs:_debugPublishCopy'.
         > Could not find com.android.support:appcompat-v7:26.1.0.
           Searched in the following locations:
               file:/Users/adrien/Library/Android/sdk/extras/android/m2repository/com/android/support/appcompat-v7/26.1.0/appcompat-v7-26.1.0.pom
               file:/Users/adrien/Library/Android/sdk/extras/android/m2repository/com/android/support/appcompat-v7/26.1.0/appcompat-v7-26.1.0.jar
               file:/Users/adrien/code/dat-react-native/android/sdk-manager/com/android/support/appcompat-v7/26.1.0/appcompat-v7-26.1.0.jar
           Required by:
               beakerReactNative:react-native-fs:unspecified > com.facebook.react:react-native:0.56.0
```

**Comment by romuloalves** [comment]
Hey @AdrienGiboire !

I don't have much knowledge about RN or Android unfortunally and because I'm away from this kind of project for some time I don't know the right answer for the JDK question! :(
Is because there's a new Android version since I started this project maybe?!

About the second item, I remember to get some messages like this but as a warning and not errors.

I think this project is not working as expected at this time and that the best approch is to take the main idea to a new one.

The thing is to use [nodejs-mobile-react-native](https://github.com/janeasystems/nodejs-mobile-react-native) to run a NodeJS server with Dat and use HTTP, Websockets, nodejs-mobile briedge or whatever to ask for archieves and render them.

I'm so sorry but I can't help you debugging at this moment!

**Comment by AdrienGiboire** [comment]
No problem :)
